---
- name: Deploy storage api
  hosts: webservers
  remote_user: root

  tasks:
  - name: Install docker.io 
    ansible.builtin.apt:
      name: docker.io
  - name: Install python3.10
    ansible.builtin.apt:
      name: python3.10
  - name: Install pip3
    ansible.builtin.apt:
      name: python3-pip
  - name: Install docker python package
    ansible.builtin.pip:
      name: docker
  - name: Ensure service is enabled
    ansible.builtin.command: service docker restart
  - name: Run docker container
    docker_container:
      name: comprobo-storage-api
      image: jonaskaz/comprobo-storage-api
      pull: yes
      state: started
      recreate: yes
      published_ports: 80:80
      volumes: 
        - /comprobo/images:/code/images
